services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $csrfTokenName: '%contao.csrf_token_name%'

    Plenta\ContaoJobsBasic\:
        resource: ../src/*
        exclude: ../src/{Entity,Migrations,Resources,Tests}

    Plenta\ContaoJobsBasic\Helper\EmploymentType:
        class: Plenta\ContaoJobsBasic\Helper\EmploymentType
        arguments:
            - '@translator'
            - '@request_stack'

    Plenta\ContaoJobsBasic\Helper\DataTypeMapper:
        class: Plenta\ContaoJobsBasic\Helper\DataTypeMapper
        arguments:
            - '@contao.framework'

    Plenta\ContaoJobsBasic\GoogleForJobs\GoogleForJobs:
        public: true
        class: Plenta\ContaoJobsBasic\GoogleForJobs\GoogleForJobs
        arguments:
            - '@contao.image.picture_factory'
            - '@contao.assets.files_context'
            - '@Plenta\ContaoJobsBasic\Helper\EmploymentType'
            - '%kernel.project_dir%'

    # Migrations
    Plenta\ContaoJobsBasic\Migration\RenameDatabaseColumnsMigration:
        public: true
        tags:
            - { name: contao.migration, priority: 0 }


    Plenta\ContaoJobsBasic\Migration\MoveRemoteJobsMigration:
        public: true
        tags:
            - { name: contao.migration, priority: 0 }

    Plenta\ContaoJobsBasic\Migration\JobLocationCountryUppercaseMigration:
        public: true
        tags:
            - { name: contao.migration, priority: 0 }

    Plenta\ContaoJobsBasic\EventListener\Contao\Hooks\ChangelanguageNavigationListener:
        public: true